In [1]:
import numpy as np

In [2]:
a = np.array([12,23,42,16,12])

In [3]:
print(a)

[12 23 42 16 12]


In [4]:
a

array([12, 23, 42, 16, 12])

In [25]:
a.ndim

1

In [5]:
type(a)

numpy.ndarray

In [7]:
x = np.array([234,56,56.00, 'Adi'])

In [8]:
x

array(['234', '56', '56.0', 'Adi'], dtype='<U32')

In [9]:
a

array([12, 23, 42, 16, 12])

In [11]:
a1 = np.array([12,23,42,16,12.00])

In [12]:
a1

array([12., 23., 42., 16., 12.])

In [13]:
a1.dtype

dtype('float64')

In [10]:
a[2]

42

In [28]:
a

array([12, 23, 42, 16, 12])

In [29]:
a[1:4]

array([23, 42, 16])

In [32]:
a[1:]

array([23, 42, 16, 12])

In [14]:
a * 2

array([24, 46, 84, 32, 24])

In [15]:
a + 2

array([14, 25, 44, 18, 14])

In [16]:
a

array([12, 23, 42, 16, 12])

In [17]:
a3 = np.arange(10)

In [18]:
a3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a3 = np.arange(2,10)
a3

array([2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a3 = np.arange(2,10,2)
a3

array([2, 4, 6, 8])

In [22]:
a3 = np.arange(-5, 5, 0.25)
a3

array([-5.  , -4.75, -4.5 , -4.25, -4.  , -3.75, -3.5 , -3.25, -3.  ,
       -2.75, -2.5 , -2.25, -2.  , -1.75, -1.5 , -1.25, -1.  , -0.75,
       -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,
        1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ,  3.25,  3.5 ,  3.75,
        4.  ,  4.25,  4.5 ,  4.75])

In [23]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 2 dimensional arrays

In [26]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [27]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
arr.ndim

2

In [34]:
arr.shape

(4, 3)

In [36]:
arr.size

12

In [35]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
arr.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [40]:
arr.reshape(6, -1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [41]:
arr.reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [42]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
arr[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [44]:
arr[1:, :2]

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [45]:
a

array([12, 23, 42, 16, 12])

In [46]:
a.max()

42

In [47]:
a.mean()

21.0

In [55]:
np.sort(a, kind= 'mergesort')

array([12, 12, 16, 23, 42])

In [56]:
np.unique(a)

array([12, 16, 23, 42])

In [57]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [66]:
np.linalg.inv(arr1)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [67]:
np.linalg.det(arr1)

-9.51619735392994e-16

In [68]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [69]:
arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [70]:
arr.reshape(3,2,2).ndim

3

In [71]:
arr.reshape(3,4,-1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])